server:
  port: 8119
  servlet:
    context-path: /restaurant-svc/api/
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

spring:
  mail:
    default-encoding: UTF-8
    host: smtp.gmail.com
    username: Nasruddin.nk44@gmail.com
    password: ${mail.password}
    port: 587
    protocol: smtp
    test-connection: false
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  datasource:
    url: jdbc:mysql://localhost:3306/restaurant-db?useSSL=false&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
springdoc:
  swagger-ui:
    path: /swagger-ui.html
file-location: /home/sufiya/my-work/files
